title: "Evolve To Control: Evolution-based Soft Actor-Critic for Scalable Reinforcement Learning"
description: "Karush Suri \\ Xiao Qi Shi \\ Yuri A. Lawryshyn \\ Konstantinos N. Plataniotis"
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
