title: "Maximum Mutation Reinforcement Learning for Scalable Control"
description: "34th Conference on Neural Information Processing Systems (NeurIPS) 2020"
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
